--liquibase formatted sql

--changeset converter:baseline dbms:mysql
CREATE TABLE `comparendo` (
  `id` varchar(36) NOT NULL,
  `fecha_imposicion` datetime NOT NULL,
  `fecha_notificacion` datetime NOT NULL,
  `fecha_registro` datetime NOT NULL,
  `observaciones` varchar(255) DEFAULT NULL,
  `valor_nominal` decimal(19,2) DEFAULT NULL,
  `agente_transito_id` int(11) NOT NULL,
  `carpeta_id` varchar(36) NOT NULL,
  `curso_comparendo_id` int(11) DEFAULT NULL,
  `decision_id` int(11) DEFAULT NULL,
  `direccion_id` int(11) NOT NULL,
  `estado_id` int(11) NOT NULL,
  `formato_id` binary(255) NOT NULL,
  `grua_id` binary(255) DEFAULT NULL,
  `imagen_id` varchar(36) NOT NULL,
  `infraccion_id` int(11) NOT NULL,
  `infractor_id` varchar(36) DEFAULT NULL,
  `inmovilizacion_id` binary(255) DEFAULT NULL,
  `licencia_id` binary(255) DEFAULT NULL,
  `numero_numero` int(11) NOT NULL,
  `patio_id` int(11) DEFAULT NULL,
  `propietario_id` varchar(36) DEFAULT NULL,
  `testigo_id` int(11) DEFAULT NULL,
  `tipo_comparendo_id` int(11) NOT NULL,
  `vehiculo_id` binary(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKr7667tlv4trtxodggpyna4njp` (`agente_transito_id`),
  KEY `FKed9p7l4cy7slx864txh4ei32c` (`carpeta_id`),
  KEY `FKn12wqrxxobdg64gcknilnq4vb` (`curso_comparendo_id`),
  KEY `FKpqbgtpqgtn0tou1mc4k7nkyjk` (`decision_id`),
  KEY `FK1wi6glemdhrg2vglj1f7xdqp0` (`direccion_id`),
  KEY `FK7dw9bmxobdp1e0449cri9sm8b` (`estado_id`),
  KEY `FKnpx4muyjdq86idut62nkeoucv` (`formato_id`),
  KEY `FKfvu662574rod68t3oh2dmvp2k` (`grua_id`),
  KEY `FKoxx5vpprxtlufttfj7x5euw2g` (`imagen_id`),
  KEY `FK31dspne6njcoy0q8bdv0vq6e1` (`infraccion_id`),
  KEY `FKd4lma44f0xnvl907eo1iv1gfj` (`infractor_id`),
  KEY `FKm3hkbdr1lfba0p00hxojd6hte` (`inmovilizacion_id`),
  KEY `FK30annfwhciegh1t0fyen7tb6w` (`licencia_id`),
  KEY `FK3rwr8blc9uiw84u6xht6w3jv6` (`numero_numero`),
  KEY `FKieaphp3q9e1jbrjyhotbchxsw` (`patio_id`),
  KEY `FKltxmnkvl5syshuvk2v1usgdoe` (`propietario_id`),
  KEY `FKrqn47jxkf85dnecdm2ab43y4s` (`testigo_id`),
  KEY `FKsc764cstbx18aytbwlq523lm1` (`tipo_comparendo_id`),
  KEY `FKo80eipan3b0o53reycofbdcir` (`vehiculo_id`),
  CONSTRAINT `FK1wi6glemdhrg2vglj1f7xdqp0` FOREIGN KEY (`direccion_id`) REFERENCES `direccion` (`id`),
  CONSTRAINT `FK30annfwhciegh1t0fyen7tb6w` FOREIGN KEY (`licencia_id`) REFERENCES `licencia` (`id`),
  CONSTRAINT `FK31dspne6njcoy0q8bdv0vq6e1` FOREIGN KEY (`infraccion_id`) REFERENCES `infraccion` (`id`),
  CONSTRAINT `FK3rwr8blc9uiw84u6xht6w3jv6` FOREIGN KEY (`numero_numero`) REFERENCES `numero_comparendo` (`numero`),
  CONSTRAINT `FK7dw9bmxobdp1e0449cri9sm8b` FOREIGN KEY (`estado_id`) REFERENCES `estado_comparendo` (`id`),
  CONSTRAINT `FKd4lma44f0xnvl907eo1iv1gfj` FOREIGN KEY (`infractor_id`) REFERENCES `persona` (`id`),
  CONSTRAINT `FKed9p7l4cy7slx864txh4ei32c` FOREIGN KEY (`carpeta_id`) REFERENCES `carpeta` (`id`),
  CONSTRAINT `FKfvu662574rod68t3oh2dmvp2k` FOREIGN KEY (`grua_id`) REFERENCES `vehiculo` (`id`),
  CONSTRAINT `FKieaphp3q9e1jbrjyhotbchxsw` FOREIGN KEY (`patio_id`) REFERENCES `patio` (`id`),
  CONSTRAINT `FKltxmnkvl5syshuvk2v1usgdoe` FOREIGN KEY (`propietario_id`) REFERENCES `persona` (`id`),
  CONSTRAINT `FKm3hkbdr1lfba0p00hxojd6hte` FOREIGN KEY (`inmovilizacion_id`) REFERENCES `inmovilizacion` (`id`),
  CONSTRAINT `FKn12wqrxxobdg64gcknilnq4vb` FOREIGN KEY (`curso_comparendo_id`) REFERENCES `curso_comparendo` (`id`),
  CONSTRAINT `FKnpx4muyjdq86idut62nkeoucv` FOREIGN KEY (`formato_id`) REFERENCES `formato_comparendo` (`id`),
  CONSTRAINT `FKo80eipan3b0o53reycofbdcir` FOREIGN KEY (`vehiculo_id`) REFERENCES `vehiculo` (`id`),
  CONSTRAINT `FKoxx5vpprxtlufttfj7x5euw2g` FOREIGN KEY (`imagen_id`) REFERENCES `documento` (`id`),
  CONSTRAINT `FKpqbgtpqgtn0tou1mc4k7nkyjk` FOREIGN KEY (`decision_id`) REFERENCES `decision_comparendo` (`id`),
  CONSTRAINT `FKr7667tlv4trtxodggpyna4njp` FOREIGN KEY (`agente_transito_id`) REFERENCES `agente_transito` (`id`),
  CONSTRAINT `FKrqn47jxkf85dnecdm2ab43y4s` FOREIGN KEY (`testigo_id`) REFERENCES `testigo` (`id`),
  CONSTRAINT `FKsc764cstbx18aytbwlq523lm1` FOREIGN KEY (`tipo_comparendo_id`) REFERENCES `tipo_comparendo` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
