--liquibase formatted sql

--changeset converter:baseline dbms:mysql
CREATE TABLE `horario_firma` (
  `id` binary(255) NOT NULL,
  `domingo` varchar(255) NOT NULL,
  `fin_domingo_am` datetime NOT NULL,
  `fin_domingo_pm` datetime NOT NULL,
  `fin_jueves_am` datetime NOT NULL,
  `fin_jueves_pm` datetime NOT NULL,
  `fin_lunes_am` datetime NOT NULL,
  `fin_lunes_pm` datetime NOT NULL,
  `fin_martes_am` datetime NOT NULL,
  `fin_martes_pm` datetime NOT NULL,
  `fin_miercoles_am` datetime NOT NULL,
  `fin_miercoles_pm` datetime NOT NULL,
  `fin_sabado_am` datetime NOT NULL,
  `fin_sabado_pm` datetime NOT NULL,
  `fin_viernes_am` datetime NOT NULL,
  `fin_viernes_pm` datetime NOT NULL,
  `inicio_domingo_am` datetime NOT NULL,
  `inicio_domingo_pm` datetime NOT NULL,
  `inicio_jueves_am` datetime NOT NULL,
  `inicio_jueves_pm` datetime NOT NULL,
  `inicio_lunes_am` datetime NOT NULL,
  `inicio_lunes_pm` datetime NOT NULL,
  `inicio_martes_am` datetime NOT NULL,
  `inicio_martes_pm` datetime NOT NULL,
  `inicio_miercoles_am` datetime NOT NULL,
  `inicio_miercoles_pm` datetime NOT NULL,
  `inicio_sabado_am` datetime NOT NULL,
  `inicio_sabado_pm` datetime NOT NULL,
  `inicio_viernes_am` datetime NOT NULL,
  `inicio_viernes_pm` datetime NOT NULL,
  `jueves` varchar(255) NOT NULL,
  `lunes` varchar(255) NOT NULL,
  `martes` varchar(255) NOT NULL,
  `miercoles` varchar(255) NOT NULL,
  `sabado` varchar(255) NOT NULL,
  `viernes` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
